config/routes.rb
Rails.application.routes.draw do
  root 'festival_bases#index'
  resources :festival_bases, path: 'festivals/'
  get 'festival/:id', to: 'festival_bases#show'
  get 'programs/new/:id', to: 'programs#new', as: 'new_programs'
  post 'programs/new/:id', to: 'programs#create', as: 'create_programs'
  get 'programs/edit/:id', to: 'programs#edit', as: 'edit_programs'
  post 'programs/edit/:id', to: 'programs#update', as: 'update_programs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :festival_base
  has_many :shows, dependent: :destroy

  validates :date, presence: true
end

app/models/festival_base.rb
class FestivalBase < ApplicationRecord
  has_many :days, dependent: :destroy

  validates :stage, presence: true
  validates :name, {presence: true, uniqueness: true}
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :day

  validates :performer, presence: true
  validates :time, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/festival_bases_controller.rb
class FestivalBasesController < ApplicationController
  before_action :set_festival, only: %i[show edit update destroy]

  def index
    @festivals = FestivalBase.all
  end

  def new
    @festival = FestivalBase.new
  end

  def create
    @festival = FestivalBase.new(festival_params)

    if @festival.save
      @festival.startDate.to_date.upto(@festival.endDate.to_date).each do |date|
        @day = Day.new(date: date.to_datetime, festival_base_id: @festival.id)
        @day.save
      end
      redirect_to new_programs_path(id: @festival.id), notice: 'Festival was successfully created.'
    else
      render :new
    end
  end

  def edit;
  end

  def update
    if @festival.update(festival_params)
      redirect_to edit_programs_path(id: @festival.id)
    else
      render :edit
    end
  end

  def show
    @days = Day.where(festival_base_id: @festival.id)
    @shows = []
    @days.each do |day|
      @showstmp = Show.where(day_id: day.id)
      @showstmp.each do |show|
        @shows << show
      end
    end
  end

  def destroy
    @festival.destroy
    redirect_to festival_bases_path, notice: 'Festival was successfully destroyed.'
  end

  private

  def set_festival
    @festival = FestivalBase.find(params[:id])
  end

  def festival_params
    params.require(:festival_base).permit(:name, :imgSrc, :startDate, :endDate, :stage)
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_festival
  before_action :set_shows, only: %i[edit]
  before_action :set_params, only: %i[create update]

  def new
  end

  def create
    i = 0
    @days.each do |day|
      puts i
      puts @performer[i]
      puts @time[i]
      @show = Show.new(day_id: day.id, performer: @performer[i], time: @time[i], date: day.date)
      @show.save
      i += 1
    end
    redirect_to festival_bases_path
  end

  def edit
  end

  def update
    i = 0
    @days.each do |day|
      puts i
      puts @performer[i]
      puts @time[i]
      Show.where(day_id: day.id).update(performer: @performer[i], time: @time[i], date: day.date)
      i += 1
    end
    redirect_to "/festival/#{@festival.id}"
  end

  def show;
  end

  private

  def set_festival
    @festival = FestivalBase.find(params[:id])
    @days = Day.where(festival_base_id: @festival.id)
  end

  def set_shows
    @shows = []
    @days.each do |day|
      @showstmp = Show.where(day_id: day.id)
      @showstmp.each do |show|
        @shows << show
      end
      puts @shows
    end
  end

  def set_params
    @performer = params.require(:performer)
    @time = params.require(:time)
  end

end

app/helpers/add_festival_helper.rb
module AddFestivalHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/festival_bases_helper.rb
module FestivalBasesHelper
end

app/views/festival/show.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="col s12">
      <%= link_to "Festivals", festivals_index_path, class: "breadcrumb" %>
      <a class="breadcrumb" href=""><%= @festival.name %></a>
    </div>
  </div>
</nav>

<div class="center">
  <%= image_tag @festival.imgSrc, :style => "height: 200px; margin-top: 20px" %>
</div>

<div class="center"><b><%= @festival.stage %></b>

  <table class="striped">
    <thead>
    <tr class="td">
      <% @days.each do |day| %>
        <th><%= l day.date, format: :date %></th>
      <% end %>
    </tr>
    </thead>

    <tbody>

    <% @days.each do |day| %>
      <tr style="display: table-cell">
        <% @shows.each do |show| %>
          <% if show.date.to_i == day.date.to_i %>
            <td style="display: block"><%= "#{show.performer} #{show.time}" %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>

    </tbody>
  </table>

  <div class="center">
    <%= link_to "Edit", add_festival_new_path, class: "waves-effect waves-light btn-large" %>

    <%= link_to festivals_index_path do %>
      <%= image_tag "https://icons-for-free.com/iconfiles/png/512/delete+remove+trash+trash+bin+trash+can+icon-1320073117929397588.png", :style => "height: 50px; margin-top: 25px; padding-top: 20px; margin-left: 20px" %>
    <% end %>
  </div>
</div>

app/views/festival_bases/_form.html.erb
<%= form_with(model: festival, local: true) do |form| %>
  <% if festival.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(festival.errors.count, "error") %> prohibited this festival from being saved:</h2>
      <ul>
        <% festival.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="row">
      <div class="field row input-field col m6">
        <div>Festival name</div>
        <%= form.text_field :name %>
        </div>
      </div>
      <div class="row">
        <div class="input col m3">
          <%= form.label 'Start date' %>
          <%= form.date_field :startDate %>
        </div>
        <div class="datepicker-calendar-container col m3">
          <%= form.label 'End date' %>
          <%= form.date_field :endDate %>
        </div>
      </div>
    <div class="row">
      <div class="input-field col m6">
        <div>Stage</div>
        <%= form.text_field :stage %>
      </div>
    </div>
    <div class="file-field input-field col m12">
      <div>Festival image url (please insert here a valid image url)</div>
      <%= form.text_field :imgSrc %>
    </div>
  </div>

  <div class="center">
    <%= link_to "Cancel", festival_bases_path, class: "waves-effect btn-large background transparent", style: "color: #5a5a5a" %>
    <div class="waves-effect"><%= form.submit "NEXT", class: "btn-large btn-large background black" %></div>
  </div>
<% end %>

app/views/festival_bases/edit.html.erb
<h1>Edit Festival</h1>

<%= render 'form', festival: @festival %>

<%= link_to 'Back', festival_bases_path %>

app/views/festival_bases/index.html.erb
<div class="row">
  <% @festivals.each { |festival| %>
    <div class="col s12 m4 l3">
      <%= link_to "/festival/#{festival.id}" do %>
        <div class="card festival-card">
          <div class="card-image">
            <%= image_tag festival.imgSrc, :style => "height: 250px" %>
            <span class="card-title"><%= festival.name %></span>
          </div>
          <div class="card-content">
            <p><%= "#{l festival.startDate, format: :date} - #{l festival.endDate, format: :date}" %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% } %>
</div>

app/views/festival_bases/new.html.erb
<h1>New Festival</h1>

<%= render 'form', festival: @festival %>

<%= link_to 'Back', festival_bases_path %>

app/views/festival_bases/show.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="col s12">
      <%= link_to "Festivals", festival_bases_path, class: "breadcrumb" %>
      <a class="breadcrumb" href=""><%= @festival.name %></a>
    </div>
  </div>
</nav>

<div class="center">
  <%= image_tag @festival.imgSrc, :style => "height: 300px; margin-top: 20px" %>
  <div class="right"><%= button_to 'DELETE', {controller: :festival_bases, action: :destroy, id: @festival.id}, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn-large background black", style: "margin-top: 20px; margin-left: -150px" %></div>
</div>

<div class="center"><b><%= @festival.stage %></b>

  <table class="striped">
    <thead>
    <tr class="td">
      <% @days.each do |day| %>
        <th><%= l day.date, format: :date %></th>
      <% end %>
    </tr>
    </thead>

    <tbody>

    <% @days.each do |day| %>
      <tr style="display: table-cell">
        <% @shows.each do |show| %>
          <% if show.day_id == day.id %>
            <td style="display: block"><%= "#{show.performer} #{show.time}" %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>

    </tbody>
  </table>

  <div class="center">
    <%= link_to "EDIT", edit_festival_basis_path, class: "waves-effect btn-large background black" %>
  </div>
</div>

app/views/festivals/index.html.erb
<div class="row">
  <% @festivals.each { |festival| %>
    <div class="col s12 m4 l3">
      <%= link_to festival_show_path do %>
        <div class="card festival-card">
          <div class="card-image">
            <%= image_tag festival.imgSrc, :style => "height: 250px" %>
            <span class="card-title"><%= festival.name %></span>
          </div>
          <div class="card-content">
            <p><%= "#{l festival.startDate, format: :date} - #{l festival.endDate, format: :date}" %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% } %>
</div>

app/views/layouts/add_festival_programs.html.erb
<div class="top-left-margin">
  <a class="waves-effect waves-light btn-large row m2" href="app/views/layouts/add_festival.html.erb">Back</a>
</div>
<div class="row"><b>Lorem stage</b>

  <div class="row">
    <div class="input col m1">
      <p>2020. 06. 06.</p>
    </div>
    <div class="datepicker-calendar-container col m6">
      <button class="waves-effect waves-light btn-large background transparent" style="color: #5a5a5a">Add show
      </button>
    </div>
  </div>
  <div class="row">
    <div class="input-field col m2">
      <input class="validate" id="performer" placeholder="Band" type="text">
      <label for="performer">Performer</label>
    </div>
    <div class="input-field col m2">
      <input class="validate" id="time" placeholder="18:00" type="text">
      <label for="time">Time</label>
    </div>
  </div>


  <div class="center">
    <a class="waves-effect btn-large background transparent" href="app/views/layouts/festivals.html.erb" style="color: #5a5a5a">Cancel</a>
    <a class="waves-effect waves-light btn-large" href="app/views/layouts/festivals.html.erb">Add festival</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>FestiGuide</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'materialize', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div id="page">
  <div id="body">
    <nav>
      <div id="menu" class="nav-wrapper">
        <%= link_to "FestiGuide", festival_bases_path, class: "left brand-logo" %>
        <ul class="right hide-on-small-and-down">
          <li><%= link_to "Festivals", festival_bases_path %></li>
          <li><%= link_to "Add new festival", new_festival_basis_path %></li>
        </ul>
      </div>
    </nav>

    <div id="main">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/programs/edit.html.erb
<div class="top-left-margin">
  <%= link_to "Back", edit_festival_basis_path, class: "waves-effect background black btn-large row m2" %>
</div>
<div class="row col m6" style="margin-left: 25px"><b><%= @festival.stage %></b>
  <%= form_with(model: @show) do |form| %>
    <% @days.each do |day| %>
      <div class="row">
        <div class="input col m2">
          <p><%= l day.date, format: :date %></p>
        </div>
      </div>
      <% @shows.each do |show| %>
        <% if show.day_id == day.id %>
          <div class="row">
            <div class="input-field col m2">
              <div>Performer</div>
              <%= form.text_field :performer, :value => show.performer, multiple: true %>
            </div>
            <div class="input-field col m2">
              <div>Time</div>
              <%= form.text_field :time, :value => show.time, multiple: true, maxlength: 6, size: 6 %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>

    <div class="center">
      <%= link_to "Cancel", festival_bases_path, class: "waves-effect btn-large background transparent", style: "color: #5a5a5a" %>
      <div class="waves-effect"><%= form.submit "EDIT FESTIVAL", class: "btn-large btn-large background black" %></div>
    </div>
  <% end %>
</div>

app/views/programs/new.html.erb
<div class="top-left-margin">
  <%= link_to "Back", edit_festival_basis_path, class: "waves-effect background black btn-large row m2" %>
</div>
<div class="row col m6" style="margin-left: 25px"><b><%= @festival.stage %></b>
  <%= form_with(model: @show) do |form| %>
    <% @days.each do |day| %>
      <div class="row">
        <div class="input col m2">
          <p><%= l day.date, format: :date %></p>
        </div>
      </div>
      <%# (0..2).each do |_| %>
      <div class="row">
        <div class="input-field col m2">
          <div>Performer</div>
          <%= form.text_field :performer, multiple: true %>
        </div>
        <div class="input-field col m2">
          <div>Time</div>
          <%= form.text_field :time, multiple: true, maxlength: 6, size: 6 %>
        </div>
      </div>
      <%# end %>
    <% end %>

    <div class="center">
      <%= link_to "Cancel", festival_bases_path, class: "waves-effect btn-large background transparent", style: "color: #5a5a5a" %>
      <div class="waves-effect"><%= form.submit "ADD FESTIVAL", class: "btn-large btn-large background black" %></div>
    </div>
  <% end %>
</div>